### PR TITLE
Integrate slides and workshops into events

### PR DESCRIPTION
**Pull request by lurkingryuu**

### CODE REVIEW

**Review by proffapt — CHANGES_REQUESTED** [review]
- `event1` -> `Event1` and so on, first letter ko capital rakho.
- https://github.com/kossiitkgp/slides/blob/main/Python-Basic-%26-Advanced/2021-March/README.md ye kahin nahi dikha
- https://github.com/kossiitkgp/events/tree/merge-slides/2019 isme ye python kya cheez hai
- Structure update kardo, `year` -> `autumn` & `spring` -> `event1`, `event2`, `event3`.
   image

**Review by proffapt — CHANGES_REQUESTED** [review]
- https://github.com/kossiitkgp/events/blob/merge-slides/2021/Autumn/Python-Basic-%26-Advanced/README.md shouldn't this be in spring semester?
- Uss python wali ka kya kiya?

**Comment by lurkingryuu** [comment]
> * Uss python wali ka kya kiya?

https://github.com/kossiitkgp/events/blob/merge-slides/2021/Autumn/Python-Basic-%26-Advanced/README.md
yahi toh tha python vala

rest Ill do asap

**Comment by lurkingryuu** [comment]
@proffapt once more :nam:

**Review by proffapt — CHANGES_REQUESTED** [review]
image
Yahan bhi capitalise kardo

**Comment by lurkingryuu** [comment]
:ahhhhhh: I hope I didn't leave out anything now
@proffapt

**Review by proffapt — APPROVED** [review]
LGTM

**Pull request merged**
